version: '3.9'

services:
  web:
    build:
      context: .
      target: development
    container_name: web
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redislabs/rejson:latest
    command: ["redis-server", "--requirepass", "key_admin", "--loadmodule", "/usr/lib/redis/modules/rejson.so"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
