title: Exec Asana Task
type: openapi
# Asana Open API Operation Name (`createTask`)
openapi: asana.1.createTask
credentials: asana.1.mycreds
hook:
  schema:
    # Asana Open API webhook payload schema
    $ref: ../schemas/openapi.yaml#/hook
input:
  schema:
    $ref: ../openapis/asana.1.0.0.yaml#/TaskRequest
  maps:
    # psdb data mapping file needed to generate the TaskRequest entity defined by the input schema
    $ref: ../maps/openapi.yaml#/input
output:
  schema:
    $ref: ../openapis/asana.1.0.0.yaml#/TaskResponse
errors:
  schema:
    $ref: ../openapis/asana.1.0.0.yaml#/TaskResponseError