openapi: 3.0.3
components:

  x-pubsubdb:
    activities:
      a1:
        title: Get Approval
        type: trigger
        settings:
          schema:
            $ref: ../schemas/order.approve.yaml#/a1_settings
          maps:
            $ref: ../maps/order.approve.yaml#/a1_settings
        input:
          schema:
            $ref: ../schemas/order.approve.yaml#/a1_input
          maps:
            $ref: ../maps/order.approve.yaml#/a1_input
        output:
          schema:
            $ref: ../schemas/order.approve.yaml#/a1_output
        return:
          schema:
            $ref: ../schemas/order.approve.yaml#/a1_return
        errors:
          schema:
            $ref: ../schemas/order.approve.yaml#/a1_errors
        stats:
          id: {$self.output.data.id}
          key: {$self.output.data.object_type}
          measures:
            - measure: count
              target: {$self.output.data.region}
            - measure: count
              target: {$self.output.data.division}
      a2:
        title: Get Approval
        type: await
        subtype: order.approve
        input:
          schema:
            $ref: ./schemas.yaml#/a2_input
        output:
          schema:
            $ref: ./schemas.yaml#/a2_output
        errors:
          schema:
            $ref: ./schemas.yaml#/a2_errors
      a3:
        title: Return True
        type: return
        input:
          # the activity, `a1`, references the `return` schema
          maps:
            $ref: '../maps/order.approve.yaml#/a3_input'
      a4:
        title: Return False
        type: return
        input:
          maps:
            $ref: '../maps/order.approve.yaml#/a4_input'

    transitions:
      a1:
        - to: a2
      a2:
        - to: a3
          conditions:
            match:
              - expected: true
                actual: {a2.hook.data.approved}
        - to: a4
          conditions:
            gate: or
            match:
              - expected: false
                actual: {a2.hook.data.approved}
              - expected: false
                actual: 
                  "@pipe":
                    - ["{a1.output.data.price}", 100]
                    - ["{number.gt}"]

    hooks:
      asana.1.taskUpdated:
        - to: a2
          conditions:
            gate: and
            match:
              - expected: {$self.output.data.task_id}
                actual: {$self.hook.data.task_id}
              - expected: completed
                actual: {$self.hook.data.status}

    subscribes: order.approve

    publishes: order.approved
