openapi: 3.0.3
components:
  x-pubsubdb:

    activities:
      a5:
        title: Review Order
        type: trigger
        settings:
          schema:
            $ref: '../schemas/order.review.yaml#/settings_a5'
          maps:
            $ref: '../maps/order.review.yaml#/settings_a5'
        input:
          schema:
            $ref: '../schemas/order.review.yaml#/input_a5'
        output:
          schema:
            $ref: '../schemas/order.review.yaml#/output_a5'
        return:
          schema:
            $ref: '../schemas/order.review.yaml#/Return1'
        errors:
          schema:
            $ref: '../schemas/order.review.yaml#/Error1'
        stats:
          key: {a5.input.data.object_type}
          id: {a5.input.data.id}
          measures:
            - measure: sum
              target: {a5.input.data.price}
            - measure: count
              target: {a5.input.data.price}
              operator: ">"
              value: 100
            - measure: avg
              target: {a5.input.data.price}
      a6:
        title: Return Review
        type: return
        input:
          maps:
            $ref: ../schemas/maps/order.review.yaml#/a6_input

    transitions:
      a5:
        - to: a6

    subscribes: order.review

    publishes: order.reviewed
